import os
import sys
import time
import re
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from bs4 import BeautifulSoup
from curl_cffi import requests

# ==========================================
# CONFIGURATION & CONSTANTS
# ==========================================
SENDER_EMAIL = os.getenv("SENDER_EMAIL", "your_email@gmail.com")
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD", "your_app_password")
RECIPIENT_EMAIL = os.getenv("RECIPIENT_EMAIL", "recipient_email@gmail.com")

TARGET_COUNTIES = ["barron-county", "polk-county", "washburn-county", "dunn-county"]
SEEN_FILE = "seen_farms.txt"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

# ==========================================
# MEMORY & PERSISTENCE
# ==========================================
def load_seen_properties():
    if not os.path.exists(SEEN_FILE):
        return set()
    with open(SEEN_FILE, "r") as f:
        return set(line.strip() for line in f if line.strip())

def save_seen_property(property_url):
    with open(SEEN_FILE, "a") as f:
        f.write(f"{property_url}\n")

# ==========================================
# EMAIL NOTIFICATION FUNCTIONS
# ==========================================
def send_rich_email_alert(title, url, county, source):
    county_formatted = county.replace('-', ' ').title()
    subject = f"🚨 NEW {source.upper()} LISTING (10+ Acres): {county_formatted}"
    
    html_body = f"""
    <html>
      <body style="font-family: Arial, sans-serif; background-color: #f4f4f9; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background: #ffffff; padding: 25px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1);">
          <span style="background-color: #2e7d32; color: white; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold;">{source} (10+ Acres)</span>
          <h2 style="color: #1b5e20; margin-top: 15px;">New Property Alert - {county_formatted}</h2>
          <p style="font-size: 16px; color: #333333;"><strong>{title}</strong></p>
          <div style="margin-top: 20px;">
            <a href="{url}" style="background-color: #2e7d32; color: white; padding: 12px 20px; text-decoration: none; border-radius: 5px; display: inline-block; font-weight: bold;">View Listing Details &rarr;</a>
          </div>
          <hr style="margin-top: 30px; border: None; border-top: 1px solid #eeeeee;">
          <p style="font-size: 12px; color: #888888;">Automated alert from Farmland Monitor System (10+ Acre Minimum Filter Applied).</p>
        </div>
      </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = SENDER_EMAIL
    msg["To"] = RECIPIENT_EMAIL
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, msg.as_string())
        print(f"  ✉️ Email alert sent for: {title}")
    except Exception as e:
        print(f"  ❌ Failed to send email: {e}")

def send_weekly_digest(seen_properties):
    subject = "📊 Farmland Monitor: Weekly Summary Digest"
    count = len(seen_properties)
    
    html_body = f"""
    <html>
      <body style="font-family: Arial, sans-serif; background-color: #f4f4f9; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background: #ffffff; padding: 25px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1);">
          <h2 style="color: #1b5e20;">Weekly Farmland Tracker Digest</h2>
          <p style="font-size: 15px; color: #333;">Here is your weekly update on monitored farmland listings across Barron, Polk, Washburn, and Dunn counties (10+ acres).</p>
          <div style="background-color: #e8f5e9; border-left: 4px solid #2e7d32; padding: 15px; margin: 20px 0;">
            <p style="margin: 0; font-size: 18px; font-weight: bold; color: #1b5e20;">Total Tracked Listings: {count}</p>
          </div>
          <p style="font-size: 14px; color: #666;">The continuous monitoring script runs hourly to catch new properties across LandWatch, LandAndFarm, and Whitetail Properties.</p>
          <hr style="margin-top: 30px; border: None; border-top: 1px solid #eeeeee;">
          <p style="font-size: 12px; color: #888888;">Weekly automated report generated by GitHub Actions.</p>
        </div>
      </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = SENDER_EMAIL
    msg["To"] = RECIPIENT_EMAIL
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, msg.as_string())
        print("  ✉️ Weekly Digest Email sent successfully!")
    except Exception as e:
        print(f"  ❌ Failed to send digest email: {e}")

# ==========================================
# SCRAPER FUNCTIONS FOR EACH DOMAIN
# ==========================================
def check_landwatch_for_county(county_slug, seen_properties):
    county_name = county_slug.replace('-', ' ').title()
    # Filter for 10+ acres added to URL path
    url = f"https://www.landwatch.com/wisconsin-land-for-sale/{county_slug}/acres-10-over"
    print(f"🔍 Searching LandWatch (10+ Acres) in [{county_name}]...")

    try:
        response = requests.get(url, headers=HEADERS, impersonate="chrome", timeout=15)
        if response.status_code != 200:
            print(f"  LandWatch status: {response.status_code}")
            return
    except Exception as e:
        print(f"⚠️ Connection error for LandWatch ({county_slug}): {e}")
        return

    soup = BeautifulSoup(response.text, "html.parser")
    property_links = soup.find_all("a", href=re.compile(r"/pid/", re.I))
    new_found_count = 0

    for a_tag in property_links:
        href = a_tag["href"]
        full_url = href if href.startswith("http") else f"https://www.landwatch.com{href}"
        title = a_tag.text.strip() or f"LandWatch Property in {county_name}"
        title = " ".join(title.split())

        if full_url not in seen_properties:
            print(f"\n🚨 NEW LANDWATCH LISTING IN {county_slug.upper()}!")
            send_rich_email_alert(title, full_url, county_slug, "LandWatch")
            save_seen_property(full_url)
            seen_properties.add(full_url)
            new_found_count += 1

    if new_found_count == 0:
        print(f"  No new LandWatch listings in {county_name}.")

def check_landandfarm_for_county(county_slug, seen_properties):
    county_name = county_slug.replace('-', ' ').title()
    # Filter for 10+ acres added to search path
    url = f"https://www.landandfarm.com/search/wisconsin/{county_slug}-land-for-sale/10-plus-acres/"
    print(f"🔍 Searching LandAndFarm (10+ Acres) in [{county_name}]...")

    try:
        response = requests.get(url, headers=HEADERS, impersonate="chrome", timeout=15)
        if response.status_code != 200:
            print(f"  LandAndFarm status: {response.status_code}")
            return
    except Exception as e:
        print(f"⚠️ Connection error for LandAndFarm ({county_slug}): {e}")
        return

    soup = BeautifulSoup(response.text, "html.parser")
    property_links = soup.find_all("a", href=re.compile(r"/(property|pid)/", re.I))
    new_found_count = 0

    for a_tag in property_links:
        href = a_tag["href"]
        full_url = href if href.startswith("http") else f"https://www.landandfarm.com{href}"
        title = a_tag.text.strip() or f"LandAndFarm Listing in {county_name}"
        title = " ".join(title.split())

        if full_url not in seen_properties:
            print(f"\n🚨 NEW LANDANDFARM LISTING IN {county_slug.upper()}!")
            send_rich_email_alert(title, full_url, county_slug, "LandAndFarm")
            save_seen_property(full_url)
            seen_properties.add(full_url)
            new_found_count += 1

    if new_found_count == 0:
        print(f"  No new LandAndFarm listings in {county_name}.")

def check_whitetail_properties(county_slug, seen_properties):
    county_name = county_slug.replace('-', ' ').title()
    url = f"https://www.whitetailproperties.com/hunting-land/wisconsin/{county_slug.replace('-county', '')}"
    print(f"🔍 Searching Whitetail Properties in [{county_name}]...")

    try:
        response = requests.get(url, headers=HEADERS, impersonate="chrome", timeout=15)
        if response.status_code != 200:
            print(f"  Whitetail Properties status: {response.status_code}")
            return
    except Exception as e:
        print(f"⚠️ Connection error for Whitetail Properties ({county_slug}): {e}")
        return

    soup = BeautifulSoup(response.text, "html.parser")
    property_links = soup.find_all("a", href=re.compile(r"/hunting-land/wisconsin/", re.I))
    new_found_count = 0

    for a_tag in property_links:
        href = a_tag["href"]
        full_url = href if href.startswith("http") else f"https://www.whitetailproperties.com{href}"
        
        # Check text title for acreage reference if present
        title = a_tag.text.strip() or f"Whitetail Properties Listing in {county_name}"
        title = " ".join(title.split())

        # Simple string check to filter out tiny parcels if acreage is mentioned in title
        acres_match = re.search(r"(\d+(?:\.\d+)?)\s*acres?", title, re.IGNORECASE)
        if acres_match:
            try:
                acres_num = float(acres_match.group(1))
                if acres_num < 10.0:
                    continue  # Skip listings under 10 acres
            except ValueError:
                pass

        if full_url not in seen_properties and full_url != url:
            print(f"\n🚨 NEW WHITETAIL PROPERTIES LISTING IN {county_slug.upper()}!")
            send_rich_email_alert(title, full_url, county_slug, "Whitetail Properties")
            save_seen_property(full_url)
            seen_properties.add(full_url)
            new_found_count += 1

    if new_found_count == 0:
        print(f"  No new Whitetail Properties listings in {county_name}.")

# ==========================================
# MAIN ENTRY POINT
# ==========================================
def main():
    seen_properties = load_seen_properties()

    # If --weekly-digest flag is passed via command line
    if "--weekly-digest" in sys.argv:
        print("📊 Sending weekly digest report...")
        send_weekly_digest(seen_properties)
        return

    print("🚀 Starting Farmland Monitor multi-site check (10+ Acre Filter)...")
    
    for county in TARGET_COUNTIES:
        check_landwatch_for_county(county, seen_properties)
        check_landandfarm_for_county(county, seen_properties)
        check_whitetail_properties(county, seen_properties)

    print("\n✅ Execution completed successfully.")

if __name__ == "__main__":
    main()